spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zakupki
    password: 12345
    username: root
    hikari:
      maximum-pool-size: 100

homyakin:
  zakupki:
    ftp:
      url: "ftp.zakupki.gov.ru"
      login: "fz223free"
      password: "fz223free"
    app:
      max-threads: 15


